name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: Xvfb :1 -screen 0 1024x768x24 </dev/null &
    - name: TestCafe
      uses: AlexKamaev/testcafe-action@v0.0.1-alpha.1
      with:
        testCafeArguments: "chrome tests --dev"
        branch: "debug-linux"
