name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: Xvfb -ac :99 -screen 0 1280x1024x16 > /dev/null 2>&1 &
    - name: TestCafe
      uses: AlexKamaev/testcafe-action@v0.0.1-alpha.1
      with:
        testCafeArguments: "chrome tests --dev"
        branch: "debug-linux"
